# Generated by Django 4.1.7 on 2023-03-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouvelle_vague', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
