# Generated by Django 4.1.7 on 2023-03-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouvelle_vague', '0002_movies_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rental_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
        migrations.AddField(
            model_name='movies',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
