# Generated by Django 4.1.7 on 2023-03-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouvelle_vague', '0003_remove_movies_movie_id_remove_rental_rental_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='overdue_flag',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='status',
        ),
        migrations.AddField(
            model_name='rental',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='movie',
            field=models.CharField(default=0, max_length=99),
            preserve_default=False,
        ),
    ]
